[workspace]

members = [
    "buildscript",
    "game",
    "ttt",
    "render",
    "asset_macro",
    "frame_lag",
    "dbe",
    "miniscript",
    "things"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package.'*']
opt-level = 3